services:
  barracuda-mapping:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barracuda-mapping
    tty: true
    network_mode: host
    volumes:
      - $HOME/.ssh:/root/.ssh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
