name: Docker Publish - barracuda-mapping

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push barracuda-mapping
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/barracuda-mapping:latest
          docker build --no-cache -t $IMAGE_NAME .
          docker push $IMAGE_NAME
